version: "3"

services:

  #server
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html


  #php
  php:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html

  #mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    volumes:
      - ./storage:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=root

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    ports:
      - "8001:80"

  #composer
  composer:
    build:
      context: docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html